export const ErrorCodes = {
  ERR_UNKNOWN_REASON: 'ERR_UNKNOWN_REASON',

  ER_NO_MOCK_FOUND: 'ERR_NO_MOCK',
  ERR_PENDING_SCOPE: 'ERR_HTTP_PENDING_SCOPE',
  ERR_INVALID_MOCK_CONFIG: 'ERR_HTTP_INVALID_MOCK_CONFIG',
  ERR_INVALID_MOCK_FILE: 'ERR_HTTP_INVALID_MOCK_FILE',
  ERR_INVALID_RESPONSE_DEFINITION: 'ERR_HTTP_INVALID_RESPONSE_DEFINITION',
  ERR_CONFIG: 'ERR_CONFIG',
  ERR_PROXY: 'ERR_PROXY_ERROR',
}
